# Generated by Django 5.2.1 on 2025-06-01 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_slug', models.SlugField(help_text='Identificador único de la pestaña (ej: home, about, event)', unique=True)),
                ('tab_nombre', models.CharField(max_length=100)),
                ('tab_description', models.TextField()),
                ('tab_url', models.URLField(blank=True, null=True, verbose_name='tab URL')),
                ('tab_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='tab_img_url_images/')),
                ('tab_file', models.FileField(blank=True, max_length=5500, null=True, upload_to='tab_file_files/')),
                ('tab_date_page', models.DateField(blank=True, help_text='Fecha de tab', null=True)),
                ('tab_time_page', models.TimeField(blank=True, help_text='Hora de tab', null=True)),
                ('tab_day_page', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el tab.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab.')),
                ('is_active', models.BooleanField(default=True, help_text='Define si este tab está activo y visible.')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=500, null=True)),
                ('country_created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se creo el tab.')),
                ('country_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab.')),
                ('country_is_active', models.BooleanField(default=True, help_text='Define si este tab está activo y visible.')),
                ('country_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(blank=True, max_length=255, null=True)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('property_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_image', models.ImageField(blank=True, max_length=5500, null=True, upload_to='properties/')),
                ('property_location', models.CharField(blank=True, max_length=2000, null=True)),
                ('property_area', models.PositiveIntegerField(blank=True, help_text='Area in Sqft', null=True)),
                ('property_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('property_bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('property_created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se creo el tab.')),
                ('property_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab.')),
                ('property_is_active', models.BooleanField(default=True, help_text='Define si este tab está activo y visible.')),
                ('property_url_link', models.URLField(blank=True, max_length=4500, null=True)),
                ('property_date_start', models.DateField()),
                ('property_time_start', models.TimeField()),
                ('property_day_start', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('property_file', models.FileField(blank=True, max_length=5500, null=True, upload_to='property_files/')),
                ('property_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noaman_manazil_app.country')),
                ('property_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyImage_image', models.ImageField(blank=True, max_length=5500, null=True, upload_to='property_gallery/')),
                ('propertyImage_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('propertyImage_is_featured', models.BooleanField(default=False)),
                ('propertyImage_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('propertyImage_created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se creo el tab.')),
                ('propertyImage_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab.')),
                ('propertyImage_is_active', models.BooleanField(default=True, help_text='Define si este tab está activo y visible.')),
                ('propertyImage_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('propertyImage_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='noaman_manazil_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noaman_manazil_app.propertytype'),
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_name', models.CharField(blank=True, max_length=500, null=True)),
                ('purpose_created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se creo el tab.')),
                ('purpose_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab.')),
                ('purpose_is_active', models.BooleanField(default=True, help_text='Define si este tab está activo y visible.')),
                ('purpose_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noaman_manazil_app.purpose'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noaman_manazil_app.status'),
        ),
        migrations.CreateModel(
            name='TabPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_page_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='tab page name')),
                ('tab_page_url_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='tab page URL name')),
                ('tab_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='tab_page_img_url_images/')),
                ('tab_file', models.FileField(blank=True, max_length=5500, null=True, upload_to='tab_page_file_files/')),
                ('tab_date_page', models.DateField(blank=True, help_text='Fecha de tab page', null=True)),
                ('tab_time_page', models.TimeField(blank=True, help_text='Hora de tab page', null=True)),
                ('tab_day_page', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el tab page.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab page.')),
                ('is_active', models.BooleanField(default=True, help_text='Define si este tab page está activo y visible.')),
                ('tab_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noaman_manazil_app.tab')),
            ],
        ),
    ]
