# Generated by Django 5.2.1 on 2025-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre Contacto')),
                ('contact_info_phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number')),
                ('contact_info_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_info_facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('contact_info_twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('contact_info_linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('contact_info_instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('contact_info_date', models.DateField(blank=True, help_text='Fecha de Contact Info', null=True)),
                ('contact_info_time', models.TimeField(blank=True, help_text='Hora de Contact Info', null=True)),
                ('contact_info_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True)),
                ('contact_info_img_url', models.ImageField(blank=True, max_length=5500, null=True, upload_to='contact_info_images/')),
                ('contact_info_file', models.FileField(blank=True, max_length=5500, null=True, upload_to='contact_info_files/')),
                ('contact_info_created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se creó el ContactInfo.')),
                ('contact_info_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el ContactInfo.')),
                ('contact_info_is_active', models.BooleanField(default=True, help_text='Define si este ContactInfo está activo y visible.')),
            ],
            options={
                'ordering': ['-contact_info_created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_message_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_message_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_message_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_message_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_message_message', models.TextField(blank=True, null=True)),
                ('contact_message_created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_message_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab page.')),
                ('contact_message_is_active', models.BooleanField(default=True, help_text='Define si este tab page está activo y visible.')),
            ],
        ),
    ]
