# Generated by Django 5.2.1 on 2025-06-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0003_contactinfo_contact_info_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_info_map_embed_url',
            field=models.TextField(blank=True, help_text="Pega aquí la URL del iframe de Google Maps (la parte del 'src').", null=True, verbose_name='URL de Google Maps embebido'),
        ),
    ]
