# Generated by Django 5.2.1 on 2025-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0004_alter_contactinfo_contact_info_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='purpose_icon',
            field=models.CharField(blank=True, help_text='Nombre del archivo de icono (ejemplo: icon-apartment.png)', max_length=255, null=True),
        ),
    ]
