# Generated by Django 5.2.1 on 2025-06-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0005_purpose_purpose_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='noaman_manazil_app.property')),
            ],
        ),
    ]
