# Generated by Django 5.2.1 on 2025-06-08 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0006_propertyreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_slide_title', models.CharField(blank=True, max_length=900, null=True)),
                ('header_slide_description', models.TextField(blank=True, null=True)),
                ('header_slide_button_text', models.CharField(blank=True, max_length=500, null=True)),
                ('header_slide_button_link', models.URLField(blank=True, null=True)),
                ('header_slide_image', models.ImageField(blank=True, null=True, upload_to='header_slides/')),
                ('header_slide_is_active', models.BooleanField(default=True)),
                ('header_slide_created_at', models.DateTimeField(auto_now_add=True)),
                ('header_slide_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el HeaderSlide.')),
                ('header_slide_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
