# Generated by Django 5.2.1 on 2025-06-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0007_headerslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerslide',
            name='header_slide_perfect_home',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='headerslide',
            name='header_slide_to_live_with',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
