# Generated by Django 5.2.1 on 2025-06-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0008_headerslide_header_slide_perfect_home_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_slide_image_image', models.ImageField(blank=True, null=True, upload_to='header_slides_images/')),
                ('header_slide_image_is_active', models.BooleanField(default=True)),
                ('header_slide_image_created_at', models.DateTimeField(auto_now_add=True)),
                ('header_slide_image_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el HeaderSlide.')),
                ('header_slide_image_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('header_slide_image_header_slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='noaman_manazil_app.headerslide')),
            ],
        ),
    ]
