# Generated by Django 5.2.1 on 2025-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0009_headerslideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
