# Generated by Django 5.2.1 on 2025-06-08 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0011_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsHeadersHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_headers_home_title_1', models.CharField(blank=True, max_length=500, null=True)),
                ('clients_headers_home_title_2', models.CharField(blank=True, max_length=500, null=True)),
                ('clients_headers_home_title_3', models.CharField(blank=True, max_length=500, null=True)),
                ('clients_headers_home_title_4', models.CharField(blank=True, max_length=500, null=True)),
                ('clients_headers_home_description_4', models.TextField(blank=True, null=True)),
                ('clients_headers_home_title_5', models.CharField(blank=True, max_length=500, null=True)),
                ('clients_headers_home_title_6', models.CharField(blank=True, max_length=500, null=True)),
                ('clients_headers_home_created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se creo el tab.')),
                ('clients_headers_home_updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el tab.')),
                ('clients_headers_home_is_active', models.BooleanField(default=True, help_text='Define si este tab está activo y visible.')),
                ('clients_headers_home_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
