# Generated by Django 5.2.1 on 2025-06-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0013_clientsheadershome_clients_headers_home_description_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsheadershome',
            name='clients_headers_home_description_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
