# Generated by Django 5.2.1 on 2025-06-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaman_manazil_app', '0014_clientsheadershome_clients_headers_home_description_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsheadershome',
            name='clients_headers_home_description_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
